name: docker image upload

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

env:
  TAG: latex-container

jobs:
  DockerImagePush:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker/setup-buildx-action@v3.9.0

      - name: docker build
        uses: ./.github/actions/dockerBuild

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        run: make push-image
        timeout-minutes: 60